apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h1edcedx2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:39c14d9943653ca756b9c12bbb7c3439723d76ce@sha256:4166cfd2a725c4516dc45c1b16c5733cbddd8d9a39647390f2c9f455027445a7
          name: container-image
